name: "PR Agent Review"
description: "A GitHub Action to review pull requests using OpenAI."
inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
  pr_number:
    description: "Pull Request Number"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    REPO_NAME: ${{ inputs.repo_name }}
    PR_NUMBER: ${{ inputs.pr_number }}
