name: "PR Agent Review"
description: "A GitHub Action to review pull requests using OpenAI."
inputs:
  openai_api_key:
    description: "API key for OpenAI"
    required: true
  github_token:
    description: "GitHub token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
