name: "PR Agent Review"
description: "A GitHub Action to review pull requests using OpenAI."
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ github.event.inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
    PR_NUMBER: ${{ github.event.inputs.pr_number }}
    INPUT_OPENAI_API_KEY: ${{ github.event.inputs.input_openai_api_key }}
    INPUT_GITHUB_TOKEN: ${{ github.event.inputs.input_github_token }}
    INPUT_PR_NUMBER: ${{ github.event.inputs.input_pr_number }}
