name: "PR Agent Review"
description: "A GitHub Action to review pull requests using OpenAI."
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  pr_number:
    description: "Pull Request Number"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PR_NUMBER: ${{ inputs.pr_number }}
