name: "PR Agent Review"
description: "A GitHub Action to review pull requests using OpenAI."
inputs:
  openai_api_key:
    description: "API key for OpenAI"
    required: true
  github_token:
    description: "GitHub token"
    required: true
  pr_number:
    description: "Pull Request Number"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PR_NUMBER: ${{ inputs.pr_number }}
    INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_PR_NUMBER: ${{ inputs.pr_number }}
steps:
  - name: "Log Input Variables"
    run: |
      echo "OPENAI_API_KEY: ${{ inputs.openai_api_key }}"
      echo "GITHUB_TOKEN: ${{ inputs.github_token }}"
      echo "PR_NUMBER: ${{ inputs.pr_number }}"
      # Optional: Redact sensitive values if logging publicly
      echo "OPENAI_API_KEY length: ${#INPUT_OPENAI_API_KEY}"
      echo "GITHUB_TOKEN length: ${#INPUT_GITHUB_TOKEN}"
      echo "PR_NUMBER: ${INPUT_PR_NUMBER}"
